### ISSUE TITLE
empty cache when language files update

### ISSUE THREAD

**Issue by mfolkeseth** [fnando/i18n-js#306]
I am having some trouble getting new translations into the I18n object. I am running i18n-js out of the box with my existing i18n setup. 

The best way I have found to solve this is by stopping the rails server, running `rake tmp:cache:clear` and then starting up the server. Not sure if the server restart is required tho.

Any better way to solve this? Maybe some info about this should be put into the readme?

**Comment by PikachuEXE** [comment]
There are some similar issues recently
like #305 & #303 
Please describe more about your environment (like versions of gem `rails` & `sprockets`)
So that we can know whether this is a duplicate issue or not.
Thanks :)

**Comment by matifol** [comment]
Rails: 3.2.14
i18n-js: 3.0.0.rc8

Hope this helps :)

**Comment by PikachuEXE** [comment]
Can you try upgrading your app to rails 4.x or create a small app with rails 4.x to see if it works?
I am afraid that the `sprockets` has some changes might have some impact on caching while I have least knowledge / test related to `sprockets`.

**Comment by matifol** [comment]
I will create a small rails app and to a test in the next few days.

**Comment by PikachuEXE** [comment]
Thanks :)

**Comment by jesperronn** [comment]
@matifol thanks for the advice to run `rake tmp:cache:clear`. I have now set our ci-build up to clear cache before it precompiles assets. 

This seems to do the trick, at least for me right now. I'm using Rails 4.2.0, i18n-js: 2.1.2

**Comment by matifol** [comment]
No problem @jesperronn ! Glad to be of help.

**Comment by irregularprofit** [comment]
Hi.

We have a similiar problem running rails 4.1.11 and i18n-js 3.0.0.rc5.
We also managed to resolve the issue by running `rake tmp:cache:clear` before `assts:precompile`.

During my search for why this happened, I came upon this ticket:
https://github.com/rails/sprockets-rails/issues/124

So it appears as if since moving the asset pipeline code from rails core into the sprockets-rails gem, running `rake assts:precompile` will no longer trigger `tmp:cache:clear`.
