### ISSUE TITLE
Using the config _with_ asset pipeline?

### ISSUE THREAD

**Issue by ezuk** [fnando/i18n-js#332]
Hello,

My Rails app (Rails 3.1.2) uses the asset pipeline, but I do want to use `config/i18n-js.yml`. Actually I don't care about the file -- I need to use the config options. ;) I want to exclude a bunch of keys, split files per locale, and all that good stuff.

The docs make it seem as though I can't use the config file (and indeed, it does nothing for me without the rake task) -- but I think I'm missing something. Is there just no way to use all of this power and flexibility when your app uses the asset pipeline?

Thank you :)

**Comment by PikachuEXE** [comment]
With current version (`3.0.0.rc9`) you can follow [the instruction in README](https://github.com/fnando/i18n-js#export-configuration-for-translations)

The `except` syntax is changed in `master` but I will just release another version soon

There is a PR #326 for pure Ruby way for gem configuration.
Check it out if interested, feedback is appreciated (and need).

**Comment by PikachuEXE** [comment]
Just released `3.0.0.rc10` instead of waiting for #326

**Comment by ezuk** [comment]
Thank you @PikachuEXE -- but the readme says "But this does not affect anything if you use Asset Pipeline." -- which is what prompted me to open this issue. :)

Does rc10 change anything about this? If so, where can I read about it? I just looked at the changelog for rc10 and did not see anything specific about the asset pipeline, but maybe I just missed it?

Thank you for your help and for maintaining the project!

**Comment by PikachuEXE** [comment]
I think the README is incorrect
Can you confirm that?

**Comment by ezuk** [comment]
Well, I have the following config on rc10:

```
translations:
  - file: "app/assets/javascripts/i18n/%{locale}.js"
    only: "js.*"
```

When running the rake task, I get the expected result. But when just starting the server (rails s or passenger), those files are not created.

Am I misunderstanding something about how it is supposed to work? (Once I have this clear, I will update the readme and submit a pull request)

**Comment by PikachuEXE** [comment]
OK, I admit the README is quite confusing and not matching the current behaviour
From reading the code (yup I don't remember how it works, which is why we need clear & up-to-date doc)

# Export
It calls `I18n::JS.export`, which calls 
- `.export_i18n_js` (copies the `i18n.js` file to somewhere)
- translation_segments.each(&:save!) (Collection of `Segment`)

# Use in asset pipeline
You properly "require" `i18n/translations`, which should include `i18n/filtered`
which calls `I18n::JS.filtered_translations`
which actually merge all `translation_segments`'s `Segment#translations` into one giant Hash

So config file should be used in BOTH cases 
except the `file` key in each entry in `translations` is only used in exporting

**Comment by PikachuEXE** [comment]
Once it makes sense I will update the README myself :P

**Comment by PikachuEXE** [comment]
By the way, your value in `only` becomes invalid in recent release
`js.*` won't work, should be `*.js.*`

**Comment by ezuk** [comment]
Thanks @PikachuEXE -- so this actually makes me take one step back. :) The reason I wanted to do this in the first place (generate the assets like this, per locale) is that I wanted to serve them per locale.

We are going to have many languages, and it is a big product. If the current session locale is, say, French, I only want the French-language hash to be included -- no reason to include 15 other big hashes. It just makes application.js really heavy.

Is there any way to accomplish that when using the asset pipeline?

**Comment by PikachuEXE** [comment]
Oops forgot to reply, sorry!

To archive this, you need to export the file by using rake task or the middleware
And the file pattern should be something like `path/to/locales/%{locale}` (mentioned in [this part of README](https://github.com/fnando/i18n-js#export-configuration-for-translations)

You also need to add it to `config.assets.precompile`
Finally you need to use helper like `javascript_include_tag` of course

**Comment by ezuk** [comment]
Thank you -- but if I use the asset pipeline, won't this result in a duplicate copy of the language files? Because the language files get stuffed into `application.js` anyway, so then I'll have both `application.js` (created automatically by the pipeline) and my `path/to/locale/%{locale}` files. Not so?

**Comment by PikachuEXE** [comment]
Translations only appears in `application.js` when you have put `//= require i18n/translations` in it.

**Comment by ezuk** [comment]
Thank you, @PikachuEXE! Closing this then. I appreciate your help!

**Comment by PikachuEXE** [comment]
I still need to update the README~

**Comment by brauliobo** [comment]
Maybe this is a duplicate of #356, and trying to require `i18n/translation` is not possible as it does not exist. I've also called `18n::JS.filtered_translations` inside a initializer, but still no help.

I understood from the last comments that the asset pipeline won't work for multiple files defined in a config file and I have to manually generate them? That would be a bad, since we use https://github.com/coletivoEITA/assets_live_compile for assets compile on the first request.

I'm looking at the source code trying to figure out a solution...

**Comment by PikachuEXE** [comment]
@brauliobo 
`i18n/translation` does exist in this project/gem
So you should be able to require it

Let's discuss #356 within that issue
