### ISSUE TITLE
Upgrading from 2.1.2 to 3.0.0rc11

### ISSUE THREAD

**Issue by nexmot** [fnando/i18n-js#351]
Hello, 

I have just updated the gem, from 2.1.2 to 3.0.0rc11. And when I start the server I get the following error:

`Valid locales: [:en, :"de-at", :"de-ch", :de, :"en-au", :"en-bork", :"en-ca", :"en-gb", :"en-ind", :nep, :"en-us", :es, :fa, :fr, :it, :ja, :ko, :"nb-no", :nl, :pl, :"pt-br", :ru, :sk, :vi, :"pt-BR", :"zh-CN", :"zh-HK", :"zh-TW", :cs, :da, :fi, :id, :no, :pt, :sv, :"gl-ES"] - Given Locales: [:"nb-no", :nb, :en]
  (in /Users/idejuan/.rvm/gems/ruby-2.1.2/gems/i18n-js-3.0.0.rc11/app/assets/javascripts/i18n/filtered.js.erb)`

Is there anything I have to configure differently in 3.0.0?

Thanks

**Comment by PikachuEXE** [comment]
This is raised from https://github.com/fnando/i18n-js/blob/master/lib/i18n/js/fallback_locales.rb#L74

This is because the gem assume you want to use fallback locales for your translations, and the code will ensure your fallback locales matches those in `I18n.available_locales` (Ruby)
I can see your `I18n.available_locales` does not have `:nb`, that's why it complains.
If that locale is missing on purpose, you can choose either of the following to remove the error:
- Set your list of fallback locales explicitly (i.e. without `:nb`)
- Disable fallback completely
Please see `Fallbacks` section in README for changing the setting

**Comment by nexmot** [comment]
thank you! I fixed it adding this line to i18n-js.yml:

`fallbacks: :default_locale`

**Comment by PikachuEXE** [comment]
Please close when appropriate :)
