### ISSUE TITLE
How does switching languages work?

### ISSUE THREAD

**Issue by deiga** [fnando/i18n-js#357]
There's no documentation on how to switch languages. I've been hacking on this a few days and it seems that one needs to rerun all `I18n.t(..)` calls after a locale switch. This solution is highly unmaintanable and I'm thinking "maybe I'm missing something here".

So I come to you for help :)

**Comment by PikachuEXE** [comment]
What are you try to achieve?
Switching locale is like doing so in Ruby:
```javascript
I18n.locale = "pt-BR";

I18n.t("...") // => Your translation
```

**Comment by deiga** [comment]
I'm trying to achieve something more dynamic than "reload the whole page" after a language switch

**Comment by PikachuEXE** [comment]
Press the button (or whatever) => something changed?
What is that something?

**Comment by j4zz** [comment]
I think I’ve run into the same question/issue. The readme suggest having a script as follows:
```html
<script type="text/javascript">
  I18n.defaultLocale = "<%= I18n.default_locale %>";
  I18n.locale = "<%= I18n.locale %>";
</script>
```

This gets processed as, for example:
```js
I18n.defaultLocale = "en";
I18n.locale = "en";
```

If you now add a button that links to a page of different locale, e.g. `/de/mypage`, and Rails picks up the new locale `de` [from the URL](http://guides.rubyonrails.org/i18n.html#setting-the-locale-from-the-url-params) for example, the processed script doesn’t get updated. So now the rails-side i18n uses a different locale than i18n-js.

How do you tell i18n-js that it has to switch locale as well?

**Comment by PikachuEXE** [comment]
When you have `/de/mypage`, you should have some code to change Ruby side `I18n.locale`
Then in the layout template that is used (In readme it uses `application.html.erb`)
and add the JS code

**Comment by j4zz** [comment]
I’m quite certain that this is what @deiga meant with [his comment](https://github.com/fnando/i18n-js/issues/357#issuecomment-138446809) on looking for something more _dynamic_. The solution you suggest works fine with a page reload. But at least if you use turbolinks and a link_to like me, it doesn’t work since a page reload is necessary to re-process the script in `application.html.erb` and pick up the changed rails `I18n.locale`.

**Comment by PikachuEXE** [comment]
I guess how to pass the "current" locale from Ruby world to JS world is really user/developer/product specific.
It can be generalized as a "how to update existing JS objects with turbolinks / AJAX" question.

**Comment by j4zz** [comment]
You’re right. Still, I suspect the original question was to inquire if i18n-js offers any best practice ways/helpers to that goal for dynamic language switching. For me, the workaround is to circumvent turbolinks for the language switchers `<%= link_to "de", params.merge(locale: :de), data: { no_turbolink: true } %>` in order to cause a reload.

**Comment by PikachuEXE** [comment]
I see.
I think `i18n-js` is only responsible for 
- generating the translations into JS form 
- provide ways to let developers "load/export" those generated JS translation objects
- provide the JS library `i18n.js` for using those translation objects

How to use the library provided (like setting `I18n.locale` to the value on Ruby side) 
should be out of this project's problem space
