### ISSUE TITLE
"Using multiple exported translation files on a page" - *with* the Rails assets pipeline

### ISSUE THREAD

**Issue by djudd** [fnando/i18n-js#407]
The README doesn't say how to do this. My first naive attempt (add files to the i18n-js.yml config in an arbitrary place, reference them in application.js etc) didn't work. Is it supported?

**Comment by PikachuEXE** [comment]
If you use rails assets pipeline, you don't need multiple exported translation files.
That's what I think.
If I am wrong please tell us more about what you expected / want to archieve

**Comment by djudd** [comment]
I don't want to serve every translation on every page. I want to split up global and route-specific translations, like the "Using multiple exported translation files on a page" section suggests.

I was able to solve this issue for now using this gem: https://github.com/camertron/i18n-js-assets

Together with the following monkeypatch for the gem:

```
module I18nJsAssets
  class Processor
    # Monkeypatch to extend existing translations, instead of overwriting completely
    def construct_javascript_for_locale(locale, translations)
      %{I18n.translations["#{locale}"] = I18n.extend((I18n.translations["#{locale}"] || {}), #{translations.to_json});\n}
    end
  end
end```

**Comment by PikachuEXE** [comment]
From reading the doc 
When you run `rake i18n:js:export` you will have `[project]/app/assets/javascripts/something.js`
if you set the config properly

Of course in order to NOT include them in your global JS, you have to avoid requiring those generated files in your global JS source

I guess you need them in development?
Then maybe you need to use `I18n::JS::Middleware` instead of using `rake i18n:js:export`
