### ISSUE TITLE
Random movie quotes and other nonesense included in filtered.js

### ISSUE THREAD

**Issue by strickland84** [fnando/i18n-js#490]
Hi there,

Shoot me down if this is not an I18n-js issue but I noticed some strange movie quotes and book quotes in my filtered-js in production. Here's a gist https://gist.github.com/strickland84/f3ab74771c07482291388c64b1599373 - please scan your eyes down that file (in full view as it's large). For example, search for the string _"Calm down, Marty. I didn't disintegrate anything. The molecular structure of both Einstein "_

The closest I could trace it down to was I18n-js. Does anyone have any ideas what could be causing this?

Note: my actual translations appear at the end of the file.

Thanks

**Comment by PikachuEXE** [comment]
What is your i18n-js config?
What are  your i18n load paths?
It could be some external library's built-in translations
So looking for non-app load paths might identify the source

Since the file is so big I can't tell what is the path to that translation key.
Otherwise you can try to search with the translation path on too (e.g. `movies.quotes`)

**Comment by strickland84** [comment]
Thanks, I think you're right - my i18n-js config is blank, haven't configured anything in particular so it must be an external library in my package.json. I'll see if I can narrow it down. I'll close this as I don't think it's and i18n-js issue.
